### ISSUE TITLE
Make use of Podfile.lock if present?

### ISSUE THREAD

**Issue by sschuberth** [segiddins/cocoapods-dependencies#16]
Just wondering about a possible optimization: When running `pod dependencies` for the first time, the whole *CocoaPods/Spec* repo gets cloned, which is taking quite some time. Wouldn't it make more sense to just parse `Podfile.lock`, if present, esp. if none of the options to create fancy graphics is specified, but all the caller wants is a list of the dependencies printed to the console?

**Comment by segiddins** [comment]
Indeed it would
