### ISSUE TITLE
not support cocoapods 1.5.3

### ISSUE THREAD

**Issue by crespoxiao** [segiddins/cocoapods-dependencies#21]
hi there,i  install this tool use gem install cocoapods-dependencies, when run pod dependencies there's an error:
[!] Unknown command: `dependencies`
Did you mean: deintegrate?

the cocoapods version I installed is 1.5.3, do you have plan to support this version ? tks.

**Comment by crespoxiao** [comment]
well, I can find dependencies in Podfile.lock

**Comment by segiddins** [comment]
Please include steps to reproduce the issue, including full output

**Comment by segiddins** [comment]
Closing due to lack of response
