### ISSUE TITLE
Unknown command: `dependencies`

### ISSUE THREAD

**Issue by lechuckcaptain** [segiddins/cocoapods-dependencies#23]
pod version: 1.7.0

After installing cocoapods-dependencies using the command:

```
gem install cocoapods-dependencies
Successfully installed cocoapods-dependencies-1.3.0
Parsing documentation for cocoapods-dependencies-1.3.0
Done installing documentation for cocoapods-dependencies after 0 seconds
1 gem installed
```

The unknown command error is printed trying to run pod dependencies command:

```
pod dependencies
[!] Unknown command: `dependencies`
Did you mean: deintegrate?
```

**Comment by segiddins** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this.

**Comment by lechuckcaptain** [comment]
I'll do, even the issue is only related to your extension. Everything related to Cocoapod works fine.

**Comment by fcamblor** [comment]
@lechuckcaptain Did you post the question on SO ? (looked for an answer, and didn't found the question)

**Comment by lechuckcaptain** [comment]
> @lechuckcaptain Did you post the question on SO ? (looked for an answer, and didn't found the question)

I actually didn't.
